---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: '00:00'
    commit-message:
      include: scope
      prefix: fix
      prefix-development: chore
